# プラグインマネージャー
[[plugins]]
repo = 'Shougo/dein.vim'

# アイコン表示
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# フィジーファインダー
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

# フィジーファインダー
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# git操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# タブとステータスバー
[[plugins]]
repo = 'vim-airline/vim-airline'

# 補完
[[plugins]]
repo = 'neoclide/coc.nvim'

# 自動で閉じタグ
[[plugins]]
repo = 'alvan/vim-closetag'

# コメントをgcで
[[plugins]]
repo = 'tomtom/tcomment_vim'

# terminalのtoggle
[[plugins]]
repo = 'kassio/neoterm'

# 画面サイズの調整
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-T>'
'''

# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# カーソル移動を簡便化
[[plugins]]
repo = 'easymotion/vim-easymotion'

# vim-surroundをドットコマンド対応に
[[plugins]]
repo = 'tpope/vim-repeat'

# 括弧を簡便化
[[plugins]]
repo = 'tpope/vim-surround'

# スクロールをスムーズに
[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

# gitの差分を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# シンタックスハイライトをより鮮やかに
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# スニペット集
[[plugins]]
repo = 'honza/vim-snippets'

# [[plugins]]
# repo = 'terryma/vim-expand-region'

# タブライン
[[plugins]]
repo = 'romgrk/barbar.nvim'

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
